#!/usr/bin/perl

# Un utilisateur doit faire partie de deux groupes : User et son nom


if (opendir(DIR, skel)) {
	close(DIR);
} else {
	mkdir "/home/skel";
	mkdir "/home/skel/Bureau";
	mkdir "/home/skel/Documents";
	mkdir "/home/skel/Documents/Ma Musique";
	mkdir "/home/skel/Public";
	mkdir "/home/skel/Téléchargements";
}

while(<>) {
	chomp;
	($nom, $prenom)= split(' ', $_);
	creer($nom, $prenom);
}


####################################
## Fonction de création d'un user ##
####################################


sub creer {
	$login		= lc( substr($nom, 0, 7) . substr($prenom, 0, 1) );
	
	$i 			= 1;
	opendir (DIR, '/home/user');
	while (readdir(DIR)) {
		if($_ eq $login) {
			$i++;
		}
	}
	$login 		.= $i 	if($i != 1);
	
	qx/ groupadd $login /;
	
	$pass		= qx/ pwgen -sA1 8 /;
	chomp $pass;

	$crypt_pass = qx/ mkpasswd -m md5 $pass /;
	chomp $crypt_pass;

	qx/ useradd $login -p '$crypt_pass' -g $login -G $login,user -d \/home\/user\/$login -k \/home\/skel -m -s \/bin\/bash /;

	open(LOG, ">>log");
	print LOG "$login;$pass\n";
	close(LOG);
}
